.test: &test
  stage: test
  script:
    - export TOXENV=''

test:3.8:
  <<: *test
  script:
    - apt-get update -qq
    - apt-get install -y -qq nodejs npm
    - npm install
    - npm run test
    - pip install tox babel
    - tox -e "flake8,py{38}-django{30}"
  tags:
    - python38



pages:
  stage: deploy
  script:
    - pip install -r requirements/dev.txt
    - pip install "Django>=3.0"
    - cd docs
    - make html
    - cd ..
    - mv docs/_build/html/ public
  artifacts:
    paths:
      - public
  tags:
    - python38
  only:
    - development

publish:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq gettext npm
    - npm install
    - pip install "Django>=3.0" "devpi-client" "babel"
    - cd planning_poker
    - /usr/local/bin/django-admin.py compilemessages
    - cd ..
    - devpi use $DEVPI_SERVER
    - devpi login --password $DEVPI_PASSWORD $DEVPI_USER
    - devpi upload --no-vcs
    - devpi upload --no-vcs --formats bdist_wheel
  only:
    - tags
    - web
  tags:
    - python38

variables:
  PIP_INDEX_URL: "https://$DEVPI_HOST/rheinwerk/dev"
  PIP_TRUSTED_HOST: "$DEVPI_HOST"
  DEVPI_SERVER: "https://$DEVPI_HOST/rheinwerk/dev/+simple/"
  DEVPI_USER: "rheinwerk"
