.test: &test
  stage: test
  script:
    - export TOXENV=''

test:2.7:
  <<: *test
  script:
    - pip install tox
    - tox -e "flake8,py{27}-django{14,16}"
  tags:
    - python27
    - debian-jessie



pages:
  stage: deploy
  script:
    - pip install -r requirements/dev.txt
    - pip install "Django>=1.6,<1.7"
    - cd docs
    - make html
    - cd ..
    - mv docs/_build/html/ public
  artifacts:
    paths:
      - public
  tags:
    - python27
    - debian-jessie
  only:
    - development

publish:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq gettext
    - pip install "Django>=1.6,<1.7"
    - cd planning_poker
    - /usr/local/bin/django-admin.py compilemessages
    - cd ..
    - devpi use $DEVPI_SERVER
    - devpi login --password $DEVPI_PASSWORD $DEVPI_USER
    - devpi upload --no-vcs
    - devpi upload --no-vcs --formats bdist_wheel
  only:
    - tags
  tags:
    - python27
    - debian-jessie

variables:
  PIP_INDEX_URL: "https://$DEVPI_HOST/rheinwerk/dev"
  PIP_TRUSTED_HOST: "$DEVPI_HOST"
  DEVPI_SERVER: "https://$DEVPI_HOST/rheinwerk/prod/+simple/"
  DEVPI_USER: "rheinwerk"
